SELECT FILIALE, EXTRACT(month FROM DATUM) AS Monat, SUM(PREIS) AS Umsatz
FROM BONDATEN 
GROUP BY FILIALE, EXTRACT(month FROM DATUM);

SELECT FILIALE, ARTIKEL.NAME, COUNT(ARTIKEL) AS Menge
FROM BONDATEN, ARTIKEL
WHERE BONDATEN.ARTIKEL = ARTIKEL.ID
AND ARTIKEL.NAME = 'Handcreme'
AND DATUM BETWEEN TO_DATE('01.09.2012', 'dd.mm.yyyy') AND TO_DATE('03.09.2012', 'dd.mm.yyyy')
GROUP BY FILIALE, ARTIKEL.NAME
ORDER BY Menge DESC;

SELECT ARTIKEL.ARTIKELGRUPPE, SUM(BONDATEN.PREIS) AS Umsatz
FROM ARTIKEL, BONDATEN
WHERE BONDATEN.ARTIKEL = ARTIKEL.ID
GROUP BY ARTIKEL.ARTIKELGRUPPE;