CREATE TABLE PREISE (
  ID NUMBER(10) NOT NULL,
  PREIS NUMBER(10,2),
  DATUM DATE,
  CONSTRAINT PREISE_PK PRIMARY KEY(ID)
);


ALTER TABLE ARTIKEL 
ADD (PREIS number(10), 
    CONSTRAINT ARTIKEL_PREIS FOREIGN KEY (PREIS) REFERENCES PREISE(ID)
    );


CREATE TRIGGER BONDATEN_PREIS
  BEFORE INSERT OR UPDATE ON BONDATEN
  FOR EACH ROW

  DECLARE
    p_preis number(10,2);
  
  BEGIN
    if(:new.preis is null) then
      select PREISE.PREIS INTO p_preis 
      FROM PREISE, ARTIKEL
      WHERE :new.ARTIKEL = ARTIKEL.ID
      AND ARTIKEL.PREIS = PREISE.ID;
    
      :new.preis := p_preis;
    END IF;
END;
/
