select * from ALL_INDEXES where OWNER = 'AAZ532';

CREATE TABLE LIEFERANTEN (
  ID NUMBER(10) NOT NULL,
  NAME VARCHAR2(50 BYTE),
  STRAßE VARCHAR2(50 BYTE),
  PLZ VARCHAR2(15 BYTE),
  STADT VARCHAR2(50 BYTE),
  EMAIL VARCHAR2(50 BYTE),
  ANSPRECHPARTNER VARCHAR2(50 BYTE),
  BEWERTUNG VARCHAR2(50 BYTE),
  CONSTRAINT PK_LIEFERANTEN PRIMARY KEY (ID)
);

INSERT INTO LIEFERANTEN 
values(1,'Maier','Hauptstraße 1','20099','Hamburg','support@Maier.de','Martin Maier','gut');

INSERT INTO LIEFERANTEN 
values(2,'Brauer KG','Hauptstraße 2','20095','Hamburg','einkauf@brauer-kg.de','Sabine Günstig','angenehm');

INSERT INTO LIEFERANTEN 
values(3,'Monte AG','Weiter Weg 42','42424','Bauersdorf','vertrieb@monte-ag.de','Carl Schlemmer','schwungvoll');

ALTER TABLE KUNDEN2 RENAME TO KUNDEN;

ALTER TABLE KUNDEN2 rename column NACHNAME to NAME;

SELECT column_name, virtual_column, segment_column_id, internal_column_id
FROM   user_tab_cols
WHERE  table_name = 'KUNDENV'
ORDER  BY column_id;

CREATE TABLE KUNDEN2 AS select * from kunden;

drop table kundenv;

CREATE TABLE GESCHÄFTSPARTNER (
  ID NUMBER(10) NOT NULL,
  NAME VARCHAR2(50 BYTE),
  STRAßE VARCHAR2(50 BYTE),
  PLZ VARCHAR2(15 BYTE),
  STADT VARCHAR2(50 BYTE),
  EMAIL VARCHAR2(50 BYTE),
  CONSTRAINT PK_GESCHÄFTSPARTNER PRIMARY KEY (ID)
);

ALTER TABLE KUNDEN 
ADD (GESCHÄFTSPARTNER_ID NUMBER(10));

ALTER TABLE KUNDEN
ADD CONSTRAINT KUNDEN_FK1 FOREIGN KEY (GESCHÄFTSPARTNER_ID) REFERENCES GESCHÄFTSPARTNER (ID) ENABLE;

ALTER TABLE LIEFERANTEN 
ADD (GESCHÄFTSPARTNER_ID NUMBER(10));

ALTER TABLE LIEFERANTEN
ADD CONSTRAINT LIEFERANTEN_FK FOREIGN KEY (GESCHÄFTSPARTNER_ID) REFERENCES GESCHÄFTSPARTNER (ID) ENABLE;

alter table KUNDEN add (email varchar2(50));


CREATE SEQUENCE GESCHÄFTSPARTNER_ID_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 15 CACHE 20;

CREATE SEQUENCE KUNDEN_ID_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 50 CACHE 20;
CREATE TRIGGER KUNDEN_TRG 
BEFORE INSERT ON KUNDEN 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT KUNDEN_ID_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

CREATE SEQUENCE LIEFERANTEN_ID_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 15 CACHE 20;
CREATE TRIGGER LIEFERANTEN_TRG 
BEFORE INSERT ON LIEFERANTEN 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT LIEFERANTEN_ID_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/


alter table kunden DROP COLUMN NAME;
alter table kunden DROP COLUMN PLZ;
alter table kunden DROP COLUMN STRAßE;
alter table kunden DROP COLUMN STADT;
alter table kunden DROP COLUMN EMAIL;

alter table lieferanten DROP COLUMN NAME;
alter table lieferanten DROP COLUMN PLZ;
alter table lieferanten DROP COLUMN STRAßE;
alter table lieferanten DROP COLUMN STADT;
alter table lieferanten DROP COLUMN EMAIL;